### ISSUE TITLE
unable to generate schedules

### ISSUE THREAD

**Issue by priyamdas** [mDibyo/berkeley-scheduler#11] opened 2016-04-28 04:50 UTC
Using Firefox, a pop-up comes up with the warning "unresponsive script"

Script: http://mdibyo.github.io/berkel…-scheduler/js/final/app.min.js:1

**Comment by mDibyo** [comment] 2016-04-28 05:46
Could you open up the console by pressing 'Ctrl+Shift+I', and then try reloading the page? Do you get any error messages there?

**Comment by mDibyo** [comment] 2016-04-28 05:47
Actually, I am quite certain why this is happening. Its the probably cuz the number of schedules that was being generated was huge. Did you add a lot of classes, or classes with many sections?

**Comment by mDibyo** [comment] 2016-04-28 05:48
If so, there's gonna be a fix for this pretty soon.

**Comment by priyamdas** [comment] 2016-04-28 05:51
The error I get is:
"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24apply
t/<@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:11:6891
h@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:13:14502
wn/this.$get</p.prototype.$digest@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:13:16786
wn/this.$get</p.prototype.$apply@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:13:18695
o/l<@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:13:26150
o@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:11:29154
ct/d.defer/n<@http://mdibyo.github.io/berkeley-scheduler/js/final/lib.min.js:11:30612
"
Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24apply

yes, I added 5 classes, 1 of which doesn't have any timings listed so that may also be causing an issue. (The no timings is not an issue with your scheduler; it's like that on the official schedule as well.)

**Comment by priyamdas** [comment] 2016-04-28 05:53
After dropping the class without timings, I was able to generate schedules! Seems like this is an edge case.

**Comment by mDibyo** [comment] 2016-04-28 17:43
Thanks for the error report! Unfortunately, I am not able to reproduce the error on my end.
Would you mind sharing the courses you were trying to schedule with (including the one with missing section times)?
You could also email this info to dibyo.majumdar@gmail.com.

**Comment by priyamdas** [comment] 2016-04-28 23:28
Sure!

Russian 1
CS61C
CS188
Psych 160
PBHLTH C129 (has no section times)

all sections were checked for each class.

Thanks for all of your hard work!

**Comment by mDibyo** [comment] 2016-08-05 09:16
I think this issue has been resolved (I can not confirm since PB HLTH C129 doesn't seem to be offered any more. ) Please reopen if you are still unable to generate schedules.

**Closed as completed by mDibyo** 2016-08-05 09:16 UTC
Labels: bug
